-- init.sql
-- run to set up assignment4 admin roles

-- DELETE FROM SECURITY_USER_SECURITY_ROLE;
-- DELETE FROM SECURITY_ROLE;
-- DELETE FROM SECURITY_USER;
-- DELETE FROM EMPLOYEE;

INSERT INTO EMPLOYEE (EMAIL, FNAME, LNAME, SALARY, TITLE) 
VALUES('dba_d00d@h2fans.org', 'Dba', 'D00d', '69420', 'DBA');
INSERT INTO EMPLOYEE (EMAIL, FNAME, LNAME, SALARY, TITLE) 
VALUES('proj_man@company.com', 'Proj', 'Ectmanager', '42069', 'Project Manager');

INSERT INTO SECURITY_ROLE (ROLENAME) 
VALUES('ADMIN_ROLE');
INSERT INTO SECURITY_ROLE (ROLENAME)
VALUES('USER_ROLE');

INSERT INTO SECURITY_USER (PWHASH, USERNAME, EMP_ID) 
VALUES('PBKDF2WithHmacSHA256:2048:lA9WZMZUGBSj2dDE4uK5tiFnMlrQm5ZKwFsAt4DBtgg=:aMfPBk93yyxFL57oZ84u2EJ0skqFum6mZwtRMuDUhk8=', 'user1', 1); 
-- VALUES('PBKDF2WithHmacSHA256:2048:lA9WZMZUGBSj2dDE4uK5tiFnMlrQm5ZKwFsAt4DBtgg=:aMfPBk93yyxFL57oZ84u2EJ0skqFum6mZwtRMuDUhk8=', 'user1', 1); 
INSERT INTO SECURITY_USER (PWHASH, USERNAME) 
VALUES('PBKDF2WithHmacSHA256:2048:CkTgfPx5Ug332e7/OMpOQOnAxvzg1zoBx42FGBz9ZxY=:3LbtObEpBeyQYeMfqrPRgTUx1sywJ8iHqXLuVIJ5wZc=', 'admin');
-- VALUES('PBKDF2WithHmacSHA256:2048:CkTgfPx5Ug332e7/OMpOQOnAxvzg1zoBx42FGBz9ZxY=:3LbtObEpBeyQYeMfqrPRgTUx1sywJ8iHqXLuVIJ5wZc=', 'admin'); 

INSERT INTO SECURITY_USER_SECURITY_ROLE (ROLE_ID, USER_ID) 
VALUES(1, 2);
INSERT INTO SECURITY_USER_SECURITY_ROLE (ROLE_ID, USER_ID) 
VALUES(2, 1);

INSERT INTO PHONE (PHONE_TYPE, AREACODE, PHONENUMBER, OWNING_EMP_ID, DEPARTMENT)
VALUES('W', '613', '555-1212', 1, 'Database');
INSERT INTO PHONE (PHONE_TYPE, AREACODE, PHONENUMBER, OWNING_EMP_ID, PROVIDER)
VALUES('M', '613', '555-2121', 2, 'Bell');
INSERT INTO PHONE (PHONE_TYPE, AREACODE, PHONENUMBER, OWNING_EMP_ID, DEPARTMENT)
VALUES('M', '613', '555-1212', 1, 'Rogers');